#!/bin/sh

#root check
if [[ `whoami` != 'root' ]]; then
	echo -en "You must run this as root\n"
	exit 1
fi

if [ $# -eq 0 ];then
	echo -en "Resetting all hubs\n"
	list=$(find /sys/bus/pci/drivers/ \
		-wholename *hci*/*:*:* -printf "%f\n")
else
	echo -en "Resetting hub $1\n"
	list=$1
fi

for hub in $list; do
	echo -en "Unbinding $hub\n"
	echo -n $hub > /sys/bus/pci/drivers/xhci_hcd/unbind
	echo -en "Binding $hub\n"
	echo -n $hub > /sys/bus/pci/drivers/xhci_hcd/bind
done
